
export const ADD_NEW_ENTITY = 'ADD_NEW_ENTITY'
export const SAVE_ENTITY = 'SAVE_ENTITY'
export const ADD_NEW_METHOD = 'ADD_NEW_METHOD'
export const SELECT_METHOD = 'SELECT_METHOD'
export const UPDATE_METHOD_BODY = 'UPDATE_METHOD_BODY'
export const INSERT_TEXT_TO_METHOD = 'INSERT_TEXT_TO_METHOD'
export const RUN_METHOD = 'RUN_METHOD'